### ISSUE TITLE
[Redux] Develop: Init new project skeleton, clone old repo, explore codebase, etc

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#117]
https://github.com/blog/1867-github-pages-now-runs-jekyll-2-2-0

**Comment by brev** [comment]
Including: "Investigate new Jekyll features" !!

**Comment by brev** [comment]
* old /tools/, /docs/ dirs?

**Comment by rhyolight** [comment]
"docs" is where I put all documentation from nupic, nupic.core, and
htm.java. It gets updated all the time, so we need to leave it.

"tools" is just a place for me to put stuff that I use. Please leave it as
well, but it's not really for public consumption.


---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by brev** [comment]
dev branch: https://github.com/brev/numenta.org/tree/gh-pages-brev-redux

**Comment by cogmission** [comment]
@brev Wow, looks excellent so far! I'm impressed! :+1:

**Comment by brev** [comment]
more init work here again: https://github.com/brev/numenta.org/tree/gh-pages-brev-redux

Recent changes:
https://github.com/brev/numenta.org/commit/2b872e69b0be9385234b7a55a5284e08d9130cbc
https://github.com/brev/numenta.org/commit/3f785ea5dfb1115dc10fca9b18722f101e91b8c5

Interesting URLs:
`/index.new.html`
`/styleguide/`

cc @rhyolight @jcasner 
@cogmission thanks! :)
