### ISSUE TITLE
Style numenta.org/docs index nicely

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#128]
Should match look and feel for the rest of the site, and provide some details about the documentation. 

http://numenta.org/docs/ currently looks like this: 

![screen shot 2014-11-13 at 2 18 56 pm](https://cloud.githubusercontent.com/assets/15566/5037918/078d6dbc-6b40-11e4-9eac-fab51d9e5763.png)

Ugly and dumb.

**Comment by brev** [comment]
will create a new docs page as part of redesign
