### ISSUE TITLE
Add a link to NuPIC Studio somewhere

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#132]

**Comment by brev** [comment]
temporarily lowering priority, I'll make sure this is part of redesign.

**Comment by brev** [comment]
already there: https://github.com/numenta/nupic/wiki/Community-Content#toward-a-universal-cortical-algorithm

**Comment by brev** [comment]
added to https://github.com/numenta/nupic/wiki/Community-Content for now, it's also linked on the wiki from other smart places already.
