### ISSUE TITLE
[Redux]: Styleguide Init

### ISSUE THREAD

**Issue by brev** [numenta/numenta.org#152]
Create intial Styleguide based off Header+Home+Footer designs, and a few other pages - rules that all pages and CSS should follow. Nice public document so contributors can follow along and help.

**Comment by rhyolight** [comment]
:+1:

**Comment by brev** [comment]
ooooooh... living style guide via KSS:

https://github.com/kss-node/kss-node
https://github.com/kss-node/kss/blob/spec/SPEC.md
https://github.com/htanjo/kss-node-template
http://htanjo.github.io/kss-node-template/
https://www.npmjs.com/package/gulp-kss

**Comment by brev** [comment]
in https://github.com/brev/numenta.org/tree/gh-pages-brev-redux

`/styleguide/` is being built and served correctly. Have a good start, will continue with other development.
