### ISSUE TITLE
[Redux] Design and Devel: Docs page (Obsolete???)

### ISSUE THREAD

**Issue by brev** [numenta/numenta.org#155]

**Comment by brev** [comment]
* Hero
  * Link back to START, DOWNLOADS, 
* Build `/docs/#build`
  * Repos/Src link-or-share with COMMUNITY:Project
  * help link: COMMUNITY:Contact
* Test `/docs/#test`
* Tutorials/Examples `/docs/#examples`
* Guides/Manuals/Code Snippets `/docs/#guides`
* APIs/Reference `/docs/#reference`
* Wiki
* FAQ link
* Help link > COMMUNITY:Contact
* Link to THEORY and COMMUNITY

**Comment by brev** [comment]
Interesting UI for this? https://helpx.adobe.com/edge-reflow/how-to/edge-reflow-common-layout.html

**Comment by rhyolight** [comment]
Not sure we'll have much control over the docs pages for `nupic`, `nupic.core`, and `htm.java`, because all those docs are generated from the code.

**Comment by brev** [comment]
Planning to stick with homepage section, instead of whole separate page, for now.

**Comment by brev** [comment]
Don't forget to Make Tests.

**Comment by brev** [comment]
future expansion and rework perhaps.
