### ISSUE TITLE
Add a 32x32 pixel version of the Numenta logo

### ISSUE THREAD

**Issue by rcrowder** [numenta/numenta.org#166]
Add into images sub-directory a 32x32 pixel PNG version of the Numenta logo.

![numenta-icon32](https://cloud.githubusercontent.com/assets/470969/6556681/0869fd0e-c667-11e4-806a-66ab9da6bb4f.png)

**Comment by rcrowder** [comment]
Thanks @rhyolight I've added an associated change here; https://github.com/rcrowder/nupic.core/commit/1552e897808ce04388aaae2d82c43a72449b9377 No rush to get this sorted. This 32x32 version will appear within the Nuget package manager alongside the nupic.core package details.

**Comment by rhyolight** [comment]
@rcrowder No problem. Easy change.
