### ISSUE TITLE
[Redux] Start section installation instructions should present differently on different OSes

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#184]
Specifically:

![screen shot 2015-05-18 at 10 38 39 am](https://cloud.githubusercontent.com/assets/15566/7686357/0f2efa44-fd4a-11e4-9619-fbfc3994c9bb.png)

- [x] For Windows, show the following:

> We're sorry, but NuPIC currently does not run on Windows. We're working on Windows support, however! In the meantime, you can try [running in a virtual machine](https://github.com/numenta/nupic/wiki/Running-Nupic-in-a-Virtual-Machine) or on [docker](https://github.com/numenta/nupic/wiki/Install-NuPIC-using-Docker). 

- [x] For Linux:

```
$ pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.2-cp27-none-linux_x86_64.whl
$ python
>>> import nupic, sys
>>> print 'nupic' in sys.modules
True
>>> # Success!
```

For OS X, the current text is correct.

**Comment by brev** [comment]
![screen shot 2015-05-22 at 10 40 51 am](https://cloud.githubusercontent.com/assets/208140/7776348/162a463c-006f-11e5-8dfc-4eb5edcb0837.png)

**Comment by rhyolight** [comment]
:+1:

**Comment by cogmission** [comment]
Or HTM.java :-P ?

On Fri, May 22, 2015 at 12:47 PM, Matthew Taylor <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/numenta.org/issues/184#issuecomment-104725954>
> .
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by brev** [comment]
![screen shot 2015-05-22 at 10 58 09 am](https://cloud.githubusercontent.com/assets/208140/7776677/821a1a50-0071-11e5-95e8-15e283d8d41a.png)

New Linux look.

**Comment by rhyolight** [comment]
:+1:

**Comment by brev** [comment]
and lastly, a Ubuntu-flavored Linux screen:

![screen shot 2015-05-22 at 11 15 26 am](https://cloud.githubusercontent.com/assets/208140/7776947/eb47b864-0073-11e5-88e7-b62cbc08be5f.png)

**Comment by rhyolight** [comment]
Wait, who says NuPIC doesn't work in Ubuntu?

**Comment by brev** [comment]
I must've been looking at old docs when I saw that, I'll make sure all Linux is treated the same with the long pip url. thanks
