### ISSUE TITLE
[Redux] Start "Download" section update text

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#185]
![screen shot 2015-05-18 at 10 43 25 am](https://cloud.githubusercontent.com/assets/15566/7686456/b94353d6-fd4a-11e4-9197-bdb95a8eaea2.png)

This download is a source code download for both Linux and OS X. The button is sortof misleading because it suggests that downloading it will install an app on the user's system. 

In the blue button:

- [x] Change "Version 0.2.1" to "Version 0.2.2" (and update link to https://github.com/numenta/nupic/releases/tag/0.2.2)
- [x] Change "OS X" to "Source Code"

Under button:
- [x] change "More platforms and versions in Downloads." to "Get older versions in Downloads."

**Comment by cogmission** [comment]
Ooooh this website is gonna be so sweet!

**Comment by brev** [comment]
thanks @cogmission :)

**Comment by brev** [comment]
@rhyolight I'll make these changes for now, but may revert in the future for #197 FYI thanks

**Comment by brev** [comment]
@rhyolight also FYI, link to current version is here: https://github.com/brev/numenta.org/blob/gh-pages-brev-redux/_data/url.yml#L54-L55

bumped to 0.2.2

**Comment by rhyolight** [comment]
Got it, thanks.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta
