### ISSUE TITLE
[Redux] Binary packages into Github Downloads page via API w/Matt

### ISSUE THREAD

**Issue by brev** [numenta/numenta.org#197]
dox:
https://developer.github.com/v3/repos/releases/#upload-a-release-asset

helpful?
https://github.com/aktau/github-release

The Goal (very badass IMHO):
https://github.com/atom/electron/releases/tag/v0.26.0

cc @rhyolight

**Comment by brev** [comment]
Revert some changes to #185 to get this working fully later.

**Comment by rhyolight** [comment]
@brev I thought about this and decided not to do it because we're uploading our binary packages into `pypi` for installation with `pip`. I'd rather have them all in one place at https://pypi.python.org/pypi/nupic rather than keep them in two places.
