### ISSUE TITLE
[Redux] Rewrite community section paragraph

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#201]
At http://brev.github.io/numenta.org/#community the paragraph below the header doesn't really describe the community. Write a new paragraph with an overview of the community and how to engage.

**Comment by brev** [comment]
FWIW Here is an edit of some rough draft text I had in that spot earlier:

> NuPIC has an open and talented community pushing together towards a new era of Machine Intelligence. Everyone is welcome to pitch in and contribute!

**Comment by brev** [comment]
Stole some other text from the current site.
