### ISSUE TITLE
[Redux] Move out-of-place community paragraph somewhere else (docs?)

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#202]
The following paragraph located at http://brev.github.io/numenta.org/#community is out of place:

> The NuPIC source code is used by Numenta as a part of a commercial product development. Because of this, it is no longer a “pure” implementation of the HTM algorithms. We have made optimizations, added tweaks, and taken some short cuts to improve performance. For those interested in studying and characterizing a purer form of the HTM, please be aware of these changes. If your interest is using NuPIC in a product, then you may be happy with the code as-is or you may want to make additional changes.

**Comment by brev** [comment]
@rhyolight How about if I move that text to the top of this main wiki page:
https://github.com/numenta/nupic/wiki/Learning-NuPIC
?

**Comment by brev** [comment]
Did the above.
