### ISSUE TITLE
[Redux] Sharing links are wrong

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#205]
Found on http://localhost:4000/blog/ but also true for individual blog posts and at http://localhost:4000/#latest (wherever those sharing icons are located together)

![screen shot 2015-05-28 at 3 28 57 pm](https://cloud.githubusercontent.com/assets/15566/7872626/5c66c6e6-054e-11e5-96da-29fc590bf82d.png)

The links seem to have bad URLs to the target resource, for example:

- http://www.facebook.com/sharer/sharer.php?u=/blog/2015/02/10/htm-java-receives-benchmark-harness.html
- http://twitter.com/share?url=/blog/2015/02/10/htm-java-receives-benchmark-harness.html
- https://plus.google.com/share?hl=en&url=/blog/2015/02/10/htm-java-receives-benchmark-harness.html

Notice the URLs are relative to the page displayed. They should be absolute.

**Comment by brev** [comment]
@rhyolight These will be absolute in Production, but missing `baseurl` on Development and Staging. I've put a note in the `README.md` about it, otherwise passing. thanks.
