### ISSUE TITLE
Update AppVeyor badge for nupic and nupic.core

### ISSUE THREAD

**Issue by rcrowder** [numenta/numenta.org#234]
Ref for core; https://github.com/numenta/nupic.core/commit/2e6ab3f1d70d9070a66b601329310fb9474128ba

@rhyolight I've locally update the nupic.core difference in the repos.yaml Can you lookup the AV nupic settings and email me the Badge Status URL. Cheers, R.

**Comment by rhyolight** [comment]
### Project status badge

SVG image URL
```
https://ci.appveyor.com/api/projects/status/px32pcil23vunml0?svg=true
```

Raster image URL
```
https://ci.appveyor.com/api/projects/status/px32pcil23vunml0
```

Sample markdown code
```
[![Build status](https://ci.appveyor.com/api/projects/status/px32pcil23vunml0?svg=true)](https://ci.appveyor.com/project/numenta-ci/nupic-core)
```

### master branch status badge

SVG branch image URL
```
https://ci.appveyor.com/api/projects/status/px32pcil23vunml0/branch/master?svg=true
```

Raster branch image URL
```
https://ci.appveyor.com/api/projects/status/px32pcil23vunml0/branch/master
```

Branch sample markdown code
```
[![Build status](https://ci.appveyor.com/api/projects/status/px32pcil23vunml0/branch/master?svg=true)](https://ci.appveyor.com/project/numenta-ci/nupic-core/branch/master)
```

**Comment by rcrowder** [comment]
@rhyolight Thanks, that looks like all the nupic.core ones. Can you also add the nupic one too pls.

**Comment by rhyolight** [comment]
## Project status badge

Current status

SVG image URL

    https://ci.appveyor.com/api/projects/status/4toemh0qtr21mk6b?svg=true

Raster image URL

    https://ci.appveyor.com/api/projects/status/4toemh0qtr21mk6b

Sample markdown code

    [![Build status](https://ci.appveyor.com/api/projects/status/4toemh0qtr21mk6b?svg=true)](https://ci.appveyor.com/project/numenta-ci/nupic)

## master branch status badge

SVG branch image URL

    https://ci.appveyor.com/api/projects/status/4toemh0qtr21mk6b/branch/master?svg=true

Raster branch image URL

    https://ci.appveyor.com/api/projects/status/4toemh0qtr21mk6b/branch/master

Branch sample markdown code

    [![Build status](https://ci.appveyor.com/api/projects/status/4toemh0qtr21mk6b/branch/master?svg=true)](https://ci.appveyor.com/project/numenta-ci/nupic/branch/master)
