### ISSUE TITLE
Update nupic installation instructions to be more realistic

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#238]
`pip install nupic` does not work on linux or windows.

**Comment by rhyolight** [comment]
as noted in https://github.com/numenta/nupic/issues/2759#issuecomment-158861822

**Comment by brev** [comment]
Looks like the wiki section there needs to be updated also? (Mac OS X needs manual nupic.bindings install).
https://github.com/numenta/nupic/blob/master/README.md#install-os-x
correct? thanks.

**Comment by brev** [comment]
What is the Mac OS X package name for nupic.bindings? I have the URL for windows:

pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl

but what about Mac OS X?
thanks

**Comment by brev** [comment]
FYI the Linux quickstart already does mention nupic.bindings

**Comment by rhyolight** [comment]
@brev OS X does not need a manual installation of `nupic.bindings`.

**Comment by brev** [comment]
@rhyolight ok, Mac doesn't need it, Linux already has it, so I guess this ticket is to add a nupic.bindings install quickstart instructions for windows?  Trying to understand still thanks!

**Comment by rhyolight** [comment]
I'm going to close this because I think we're going to do a complete content scrub on numenta.org soon.
