### ISSUE TITLE
Broken links on theory page

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#261]
http://numenta.org/#theory

The first two links under both the left and right columns entitled:
* Principles of Hierarchical Temporal Memory (HTM) - Foundations of Machine Intelligence
* What the Brain Says about Machine Intelligence

**Comment by cogmission** [comment]
I didn't check _all_ of them. I would run through all the links on that page to be sure?

**Comment by rhyolight** [comment]
The three that have broken links currently are:
 
1) Principles of Hierarchical Temporal Memory (HTM) - Foundations of Machine Intelligence
And
2) What the Brain Says about Machine Intelligence  
 
Both should now point to: http://numenta.com/learn/htm-videos-from-jeff-hawkins.html
 
3) Properties of SDRs and their Application to HTM should point to http://arxiv.org/abs/1503.07469
