### ISSUE TITLE
Devel: Populate new Media/Press section with included links

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#62]
I want a place where we can link to articles, press stuff, blog posts, etc. that are not created by the NuPIC community, but are relevant to NuPIC and Numenta. 

- http://doubleclix.wordpress.com/2013/04/14/is-our-neocortex-a-giant-semantic-bloom-filter-of-natural-intelligence-machine-learning-jeff-hawkins/
- http://www.grahamlea.com/2013/12/computing-like-brain-machine-intelligence-jeff-hawkins-yow-2013/
- http://www.infoworld.com/d/open-source-software/jeff-hawkins-where-open-source-and-machine-learning-meet-big-data-224069
- http://www.jeffkramer.com/2013/12/30/book-review-on-intelligence-by-jeff-hawkins/

**Comment by brev** [comment]
With new redesign site, Media page will be more of Media+Press, and should cover this.

**Comment by rhyolight** [comment]
I'm going to reopen this just so we don't forget about the links in the description. We can close once they are in place on the page.

**Comment by brev** [comment]
thanks, I'll copy the links over to https://github.com/numenta/numenta.org/issues/162 so I won't miss them
