### ISSUE TITLE
[Redux] Design: Terms of Service

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta.org#90]
From: https://issues.numenta.org/browse/NPC-202

We need a page to put a copyright notice regarding the content on numenta.org and the mailing list(s). We also need to put the translation copyright here.

Donna is still reviewing the verbiage, but:

> Numenta(Translation(License
> 
> Copyright (c) 2010, 2011 Numenta, Inc.
> 
> All rights reserved.
> 
> The text, algorithms, sample code, pseudo code and other work included herein are based upon or translated from certain works related to hierarchical temporal memory (“HTM”) technology published by Numenta Inc. Numenta holds the copyright in the original works and patent rights related to HTM and the algorithms translated herein. Numenta has agreed not to assert its patent rights against development or use of independent HTM systems for contributors to the NuPIC open source project at numenta.org. Any proprietary use of HTM technology that infringes on Numenta’s patents will require a commercial license from Numenta.
> 
> Based on the foregoing, Numenta grants you a license to use these algorithms and works. For purposes of this license, "proprietary use" includes training an HTM network with the intent of later deploying the trained network or application without also releasing all modifications to the NuPIC open source project, and using or permitting others to use the output from HTM technology for proprietary purposes. Any distribution, publication, or copying of this work must include the full text of this Translation License in both English and the target language.
> 
> NO EXPRESS OR IMPLIED LICENSES TO ANY PATENT RIGHTS ARE GRANTED BY THIS LICENSE. NUMENTA SPECIFICALLY DISCLAIMS ANY LIABILITY OR RESPONSIBILITY FOR THE QUALITY OR ACCURACY OF ANY TRANSLATIONS LICENSED HEREUNDER.

**Comment by brev** [comment]
see also: http://numenta.com/legal/terms.html

**Comment by brev** [comment]
this is taken care of in #157
